name: Elixir CI

on:
  push:
    branches: [master, release/*]
  pull_request:
    branches: [master]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v2

      - name: set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.10.4"
          otp-version: "22.3"

      - name: build container image
        run: docker build -t registry.digitalocean.com/profitmargin/elixir-kube-ocean:$(echo $GITHUB_SHA | head -c8) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/profitmargin/elixir-kube-ocean
