name: Elixir CI

on:
  push:
    branches: [master, release/*]
  pull_request:
    branches: [master]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v2

      - name: set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.10.4"
          otp-version: "22.3"

      - name: build container image
        run: docker build -t registry.digitalocean.com/profitmargin/elixir-kube-ocean:$(echo $GITHUB_SHA | head -c7) .

      - name: restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: install dependencies
        run: mix deps.get

      - name: run tests
        run: mix test
